<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="i-bar"></span>
                <span class="i-bar"></span>
                <span class="i-bar"></span>
            </a>
            <a class="brand" href="/">Bluz</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="/">Home</a></li>
                    <li class="dropdown" id="menu-tests">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#menu-tests">
                            Tests
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><?= $this->Ahref('Controls', $this->Url(array('controller' => 'controls'), 'test'))?></li>
                            <li><?= $this->Ahref('Markup', $this->Url(array('controller' => 'markup'), 'test'));?></li>
                        </ul>
                    </li>
                </ul>
                <? if (isset($identity) && $identity) : ?>
                    <p class="navbar-text pull-right">
                        Logged in as <?= $this->Ahref($identity->login, $this->Url(array('id' => $identity->id), 'users-profile'))?>
                        (<a href="<?= $this->Url(array('controller' => 'logout'), 'users')?>">logout</a>)
                    </p>
                <? else: ?>
                    <ul class="nav pull-right">
                        <li><a href="<?= $this->Url(array('controller' => 'login'), 'users')?>">Login</a></li>
                    </ul>
                <? endif; ?>
                <div id="loading"></div>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>

